version: "3"

services:
  flarum:
    image: mondedie/flarum:stable
    container_name: flarum
    env_file:
      - ./mnt/docker/flarum/flarum.env
    volumes:
      - ./mnt/docker/flarum/assets:/flarum/app/public/assets
      - ./mnt/docker/flarum/extensions:/flarum/app/extensions
      - ./mnt/docker/flarum/storage/logs:/flarum/app/storage/logs
      - ./mnt/docker/flarum/nginx:/etc/nginx/flarum
    ports:
      - 8081:8888
    depends_on:
      - mariadb_flarum
  mariadb_flarum:
    image: mariadb:10.5
    container_name: mariadb_flarum
    environment:
      MARIADB_ROOT_PASSWORD: password1234*
      MARIADB_DATABASE: flarum
      MARIADB_USER: flarum
      MARIADB_PASSWORD: flarum_itds362
    volumes:
      - ./mnt/docker/mysql/db:/var/lib/mysql
